### ISSUE TITLE
Problem with Advert playlist not advancing

### ISSUE THREAD

**Issue by zachwhalen** [colloqi/piSignage#288]
Hello,

I am attempting to use an advertisement playlist. It is currently a set of PNG files with the setting to play 3 assets every 5 minutes, and each asset (PNG file) in the advertisement playlist is set to display for 10 seconds. Most of the assets in the main playlist are YouTube videos.

I have two players in this group, and ~only one is affected.~ and both are affected.

The player will switch to the advertising playlist, display the first image ... and then nothing else. It never advances past that image. 

Manually advancing the player works, and the rest of the assets display as expected. 

In case it's helpful, here is an excerpt from that player's `forever_out` log from the time when it got stuck: 

```
2025-03-19T16:50:19: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"setZones","params":{"fullscreen":true,"main":{"type":"image","path":"/media/Health Communication Pres.png"}},"token":141},"token":141}
2025-03-19T16:50:19: MEDIA_ENDED message from browser: https://youtu.be/H2p_FtnUZAI, zone: main and screen: 0
2025-03-19T16:50:19: display next timer cancelled: main
2025-03-19T16:50:19: *** skipping scheduler with callIndex: 31 mismatch with 32
2025-03-19T16:51:00: Student Work: Playlist is eligible for schedule
2025-03-19T16:51:00: Promo: Playlist is eligible for schedule
2025-03-19T16:51:24: server send: ["upload","4000000067cf6998","/home/pi/forever_out.log","2025-03-19T14:46:19: Change playlist,deleting files: _local_bumper_computer_8s.mkv,_local_bumper_eye_8s.mkv,_local_bumper_logo_1_8s.mkv,_local_bumper_megaphone_8s.mkv,default.tmp\n2025-03-19T14:46:19: the total SD card usage, total: 29G,used: 7.1G,available: 20G\n2025-03-19T14:46:19: *** Changing Playlist *** to Student Work 3/19/2025, 2:46:19 PM\n2025-03-19T14:46:19: ****** new socket connection from chrome *****\n2025-03-19T14:46:19: Chrome loaded page for screen: 0 /layouts/1.html;?screen=0&token=867\n2025-03-19T14:51:11: Evince windowID :  evince\n2025-03-19T14:57:36: Evince windowID :  evince\n2025-03-19T15:04:18: Evince windowID :  evince\n2025-03-19T15:10:59: Evince windowID :  evince\n2025-03-19T15:17:37: Evince windowID :  evince\n2025-03-19T15:28:53: Evince windowID :  evince\n2025-03-19T15:34:52: Evince windowID :  evince\n2025-03-19T15:41:16: Evince windowID :  evince\n2025-03-19T15:48:10: Evince windowID :  evince\n2
2025-03-19T16:51:24: Websocket: received message from server: ["upload_ack","/home/pi/forever_out.log"]
```

UPDATE: this issue is not restricted to the advertising playlist, but shows up with some (though not all) PNG files, and for these PNG files, they sometimes work normally and sometimes freeze the playlist.

**Comment by zachwhalen** [comment]
I converted all of the PNGs to PDFs, and I disabled the group's transition animation. Still freezing.

**Comment by colloqi** [comment]
Can you write to support at pisignage.com with your account name and player name. Also can you increase the duration of advt  asset to 20 second, change YouTube duration and try. Looks like YouTube media event and duration is calling callback twiice

**Comment by zachwhalen** [comment]
Hello,

I have some more information. I deleted the advertising playlist and made a new playlist just for testing. This had three assets: 
1. a local media file
2. a youtube video link
3. a pdf (set to 20 seconds)

It cycled through correctly one time and then froze on the pdf. I will paste the relevant log below. The problem seems to start at `2025-03-21T06:54:37: display next timer cancelled: main`.

Please let me know if you have any insight.

Thanks,
zw


```stdout: 2025-03-21T06:51:46:             "old": [],
2025-03-21T06:51:46:             "new": []
2025-03-21T06:51:46:         }
2025-03-21T06:51:46:     }
2025-03-21T06:51:46: ]
2025-03-21T06:51:46: store obersver for LOUNGE and forceRestart is true
2025-03-21T06:51:46: {"scheduledAudioPlaylists":[],"justUpdateState":false}
2025-03-21T06:51:46: Stopping Lounge music
2025-03-21T06:51:46: State observer for diff: ADVERTS
2025-03-21T06:51:46: [
2025-03-21T06:51:46:     {
2025-03-21T06:51:46:         "scheduledAdvertPlaylists": {
2025-03-21T06:51:46:             "old": [],
2025-03-21T06:51:46:             "new": []
2025-03-21T06:51:46:         }
2025-03-21T06:51:46:     }
2025-03-21T06:51:46: ]
2025-03-21T06:51:46: store obersver for ADVERTS and forceRestart is true
2025-03-21T06:51:46: {"scheduledAdvertPlaylists":[],"justUpdateState":false}
2025-03-21T06:51:46: inside delete unwanted assets:  [
2025-03-21T06:51:46:   'Bumper 1.local',
2025-03-21T06:51:46:   'Where Am I Owen.tv',
2025-03-21T06:51:46:   'dgst302.pdf',
2025-03-21T06:51:46:   '__TESTING.json'
2025-03-21T06:51:46: ]
2025-03-21T06:51:46: Change playlist,deleting files: _local_bumper_logo_1_8s.mkv,default.tmp
2025-03-21T06:51:46: Getting screens for configTicker,all as 0
2025-03-21T06:51:46: ****** send message for token: 773
2025-03-21T06:51:46: {
2025-03-21T06:51:46:   show: false,
2025-03-21T06:51:46:   link: 'https://pisignage.com',
2025-03-21T06:51:46:   posX: 'l',
2025-03-21T06:51:46:   posY: 't',
2025-03-21T06:51:46:   fileName: '_out_qrcode.png'
2025-03-21T06:51:46: }
2025-03-21T06:51:46: State observer for diff: PLAYLISTS
2025-03-21T06:51:46: [
2025-03-21T06:51:46:     {
2025-03-21T06:51:46:         "scheduledPlaylists": {
2025-03-21T06:51:46:             "old": [
2025-03-21T06:51:46:                 "TESTING"
2025-03-21T06:51:46:             ],
2025-03-21T06:51:46:             "new": [
2025-03-21T06:51:46:                 "TESTING"
2025-03-21T06:51:46:             ]
2025-03-21T06:51:46:         }
2025-03-21T06:51:46:     }
2025-03-21T06:51:46: ]
2025-03-21T06:51:46: store obersver for PLAYLISTS and forceRestart is true
2025-03-21T06:51:46: {"scheduledPlaylists":["TESTING"],"playlistOn":true,"groupTicker":null,"playlistTriggerType":"regular","justUpdateState":false}
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 773
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"configTicker","params":{"behavior":"slide","textSpeed":3,"message":null,"style":"","tickerHeight":"60px"},"token":773,"error":{}},"token":773}
2025-03-21T06:51:46: the total SD card usage, total: 29G,used: 7.1G,available: 20G
2025-03-21T06:51:46: Getting screens for stopVideo,all as 0
2025-03-21T06:51:46: ****** send message for token: 774
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 774
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopVideo","params":{"zone":"main"},"token":774,"error":"DOM element is not of media type"},"token":774}
2025-03-21T06:51:46: Getting screens for stopVideo,all as 0
2025-03-21T06:51:46: ****** send message for token: 775
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 775
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopVideo","params":{"zone":"side"},"token":775,"error":"DOM element is not of media type"},"token":775}
2025-03-21T06:51:46: Getting screens for stopVideo,all as 0
2025-03-21T06:51:46: ****** send message for token: 776
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 776
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopVideo","params":{"zone":"bottom"},"token":776,"error":"DOM element is not of media type"},"token":776}
2025-03-21T06:51:46: Getting screens for stopVideo,all as 0
2025-03-21T06:51:46: ****** send message for token: 777
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 777
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopVideo","params":{"zone":"zone4"},"token":777,"error":"DOM element is not of media type"},"token":777}
2025-03-21T06:51:46: Getting screens for clearZoneAll,all as 0
2025-03-21T06:51:46: ****** send message for token: 778
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 778
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"clearZoneAll","params":{},"token":778},"token":778}
2025-03-21T06:51:46: Getting screens for stopAudio,all as 0
2025-03-21T06:51:46: ****** send message for token: 779
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 779
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopAudio","params":{},"token":779,"error":null},"token":779}
2025-03-21T06:51:46: Getting screens for configTicker,all as 0
2025-03-21T06:51:46: ****** send message for token: 780
2025-03-21T06:51:46: *** Changing Playlist *** to TESTING 3/21/2025, 6:51:46 AM
2025-03-21T06:51:46: server send: ["status",{"version":"5.3.4","platform_version":"532_12_script_2024-12-07","cpuSerialNumber":"4000000067cf6998","legacyCpuSerialNumber":"","myIpAddress":"10.4.10.219 ","ethMac":"2c:cf:67:cf:69:98","wifiMac":"2c:cf:67:cf:69:99","name":"CDSTV2"},{"diskSpaceUsed":"27%","diskSpaceAvailable":"20G","totalDiskSpace":"29G","wgetSpeed":0,"wgetBytes":"0K","downloadInProgress":false,"lastUpload":1742554306555,"syncInProgress":false,"tvStatus":true,"cecTvStatus":true,"isCecNotSupported":false,"licensed":true,"uptime":"85624.92","piTemperature":52.35,"currentPlaylist":"TESTING","playlistOn":true,"duration":null,"request":true},false]
2025-03-21T06:51:46: Getting screens for uri,0 as 0
2025-03-21T06:51:46: ****** send message for token: 781
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 780
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"configTicker","params":{"message":null},"token":780,"error":{}},"token":780}
2025-03-21T06:51:46: pending tokens: 781
2025-03-21T06:51:46: Adding sub asset: Bumper 1.local of type: local
2025-03-21T06:51:46: Using local folder file /home/pi/local_media/bumper_logo_1_8s.mkv
2025-03-21T06:51:46: ****** new socket connection from chrome *****
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 781
2025-03-21T06:51:46: Chrome loaded page for screen: 0 /layouts/1.html;?screen=0&token=781
2025-03-21T06:51:46: Getting screens for config,0 as 0
2025-03-21T06:51:46: ****** send message for token: 782
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 782
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"config","params":{"animationType":"none","signageBackgroundColor":"#000","urlReloadDisable":true,"videoKeepAspect":false,"portrait":0,"fitImage":2},"token"
2025-03-21T06:51:46: Getting screens for configTicker,all as 0
2025-03-21T06:51:46: ****** send message for token: 783
2025-03-21T06:51:46: Zone: main, Playing next file: /media/_local_bumper_logo_1_8s.mkv of type video for duration 10 seconds;133;0
2025-03-21T06:51:46: Video parameters: 0,120000,0
2025-03-21T06:51:46: Calling selected video player for playVideo, cvlc
2025-03-21T06:51:46: Getting screens for stopAudio,all as 0
2025-03-21T06:51:46: ****** send message for token: 784
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 783
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"configTicker","params":{"message":null},"token":783,"error":{}},"token":783}
2025-03-21T06:51:46: pending tokens: 784
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 784
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopAudio","params":{},"token":784,"error":null},"token":784}
2025-03-21T06:51:46: Getting screens for clearZoneAll,all as 0
2025-03-21T06:51:46: ****** send message for token: 785
2025-03-21T06:51:46: ****** resolve send message for token for screen: 0: 785
2025-03-21T06:51:46: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"clearZoneAll","params":{},"token":785},"token":785}
2025-03-21T06:51:46: Playing video file: /home/pi/local_media/bumper_logo_1_8s.mkv with parameters --no-osd,--play-and-exit,--gain=1,--global-key-next=n,--file-caching=5000,--wl-display,--fullscreen,/home/pi/local_media/bumper_logo_1_8s.mkv
2025-03-21T06:51:56: cvlc exit event with code:0,signal:null
2025-03-21T06:51:56: display next timer cancelled: main
2025-03-21T06:51:56: Zone: main, Playing next file: Where Am I Owen.tv of type tv for duration 64 seconds;134;0
2025-03-21T06:51:56: Getting screens for clearZoneAll,all as 0
2025-03-21T06:51:56: ****** send message for token: 786
2025-03-21T06:51:56: ****** resolve send message for token for screen: 0: 786
2025-03-21T06:51:56: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"clearZoneAll","params":{},"token":786},"token":786}
2025-03-21T06:51:56: Getting screens for stopAudio,all as 0
2025-03-21T06:51:56: ****** send message for token: 787
2025-03-21T06:51:56: ****** resolve send message for token for screen: 0: 787
2025-03-21T06:51:56: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopAudio","params":{},"token":787,"error":null},"token":787}
2025-03-21T06:51:56: Getting screens for setZones,0 as 0
2025-03-21T06:51:56: ****** send message for token: 788
2025-03-21T06:51:56: ****** resolve send message for token for screen: 0: 788
2025-03-21T06:51:56: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"setZones","params":{"fullscreen":true,"main":{"type":"iframe","path":"https://youtu.be/RMipfgqQD2Y","assetType":"weblink","mute":false}},"token":788},"toke
2025-03-21T06:51:56: Browser stderr: [1812:1876:0321/065156.060446:ERROR:v4l2_utils.cc(584)] Could not open /dev/video10: No such file or directory (2)
2025-03-21T06:51:56: 
2025-03-21T06:51:56: Browser stderr: [1812:1876:0321/065156.322141:ERROR:v4l2_utils.cc(584)] Could not open /dev/video10: No such file or directory (2)
2025-03-21T06:51:56: 
2025-03-21T06:52:22: max temperature:  55.65
2025-03-21T06:52:22: Player uptime :  85924.94
2025-03-21T06:52:22: server send: ["status",{"version":"5.3.4","platform_version":"532_12_script_2024-12-07","cpuSerialNumber":"4000000067cf6998","legacyCpuSerialNumber":"","myIpAddress":"10.4.10.219 ","ethMac":"2c:cf:67:cf:69:98","wifiMac":"2c:cf:67:cf:69:99","name":"CDSTV2"},{"diskSpaceUsed":"27%","diskSpaceAvailable":"20G","totalDiskSpace":"29G","wgetSpeed":0,"wgetBytes":"0K","downloadInProgress":false,"lastUpload":1742554306555,"syncInProgress":false,"tvStatus":true,"cecTvStatus":true,"isCecNotSupported":false,"licensed":true,"uptime":"85924.94","piTemperature":55.65,"currentPlaylist":"TESTING","playlistOn":true,"duration":null,"request":true},false]
2025-03-21T06:53:00: Getting screens for stopVideo,all as 0
2025-03-21T06:53:00: ****** send message for token: 789
2025-03-21T06:53:00: ****** resolve send message for token for screen: 0: 789
2025-03-21T06:53:00: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopVideo","params":{"zone":"main"},"token":789,"error":"DOM element is not of media type"},"token":789}
2025-03-21T06:53:00: Zone: main, Playing next file: dgst302.pdf of type pdf for duration 20 seconds;135;0
2025-03-21T06:53:00: Getting screens for setZones,0 as 0
2025-03-21T06:53:00: ****** send message for token: 790
2025-03-21T06:53:00: ****** resolve send message for token for screen: 0: 790
2025-03-21T06:53:00: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"setZones","params":{"fullscreen":true,"main":{"type":"pdf","path":"/media/dgst302.pdf","pdfPageDuration":null,"pdfPageChange":false}},"token":790},"token":
2025-03-21T06:53:23: Zone: main, Playing next file: /media/_local_bumper_logo_1_8s.mkv of type video for duration 10 seconds;136;0
2025-03-21T06:53:23: Video parameters: 0,120000,0
2025-03-21T06:53:23: Calling selected video player for playVideo, cvlc
2025-03-21T06:53:23: Getting screens for stopAudio,all as 0
2025-03-21T06:53:23: ****** send message for token: 791
2025-03-21T06:53:23: ****** resolve send message for token for screen: 0: 791
2025-03-21T06:53:23: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopAudio","params":{},"token":791,"error":null},"token":791}
2025-03-21T06:53:23: Getting screens for clearZoneAll,all as 0
2025-03-21T06:53:23: ****** send message for token: 792
2025-03-21T06:53:23: ****** resolve send message for token for screen: 0: 792
2025-03-21T06:53:23: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"clearZoneAll","params":{},"token":792},"token":792}
2025-03-21T06:53:23: Playing video file: /home/pi/local_media/bumper_logo_1_8s.mkv with parameters --no-osd,--play-and-exit,--gain=1,--global-key-next=n,--file-caching=5000,--wl-display,--fullscreen,/home/pi/local_media/bumper_logo_1_8s.mkv
2025-03-21T06:53:32: cvlc exit event with code:0,signal:null
2025-03-21T06:53:32: display next timer cancelled: main
2025-03-21T06:53:32: Zone: main, Playing next file: Where Am I Owen.tv of type tv for duration 64 seconds;137;0
2025-03-21T06:53:32: Getting screens for clearZoneAll,all as 0
2025-03-21T06:53:32: ****** send message for token: 793
2025-03-21T06:53:32: ****** resolve send message for token for screen: 0: 793
2025-03-21T06:53:32: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"clearZoneAll","params":{},"token":793},"token":793}
2025-03-21T06:53:32: Getting screens for stopAudio,all as 0
2025-03-21T06:53:32: ****** send message for token: 794
2025-03-21T06:53:32: ****** resolve send message for token for screen: 0: 794
2025-03-21T06:53:32: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopAudio","params":{},"token":794,"error":null},"token":794}
2025-03-21T06:53:32: Getting screens for setZones,0 as 0
2025-03-21T06:53:32: ****** send message for token: 795
2025-03-21T06:53:32: ****** resolve send message for token for screen: 0: 795
2025-03-21T06:53:32: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"setZones","params":{"fullscreen":true,"main":{"type":"iframe","path":"https://youtu.be/RMipfgqQD2Y","assetType":"weblink","mute":false}},"token":795},"toke
2025-03-21T06:53:32: Browser stderr: [1812:1876:0321/065332.260989:ERROR:v4l2_utils.cc(584)] Could not open /dev/video10: No such file or directory (2)
2025-03-21T06:53:32: 
2025-03-21T06:53:32: Browser stderr: [1812:1876:0321/065332.473418:ERROR:v4l2_utils.cc(584)] Could not open /dev/video10: No such file or directory (2)
2025-03-21T06:53:32: 
2025-03-21T06:54:36: Getting screens for stopVideo,all as 0
2025-03-21T06:54:36: ****** send message for token: 796
2025-03-21T06:54:36: ****** resolve send message for token for screen: 0: 796
2025-03-21T06:54:36: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"stopVideo","params":{"zone":"main"},"token":796,"error":"DOM element is not of media type"},"token":796}
2025-03-21T06:54:36: Zone: main, Playing next file: dgst302.pdf of type pdf for duration 20 seconds;138;0
2025-03-21T06:54:36: Getting screens for setZones,0 as 0
2025-03-21T06:54:36: ****** send message for token: 797
2025-03-21T06:54:36: ****** resolve send message for token for screen: 0: 797
2025-03-21T06:54:36: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"setZones","params":{"fullscreen":true,"main":{"type":"pdf","path":"/media/dgst302.pdf","pdfPageDuration":null,"pdfPageChange":false}},"token":797},"token":
2025-03-21T06:54:37: MEDIA_ENDED message from browser: https://youtu.be/RMipfgqQD2Y, zone: main and screen: 0
2025-03-21T06:54:37: display next timer cancelled: main
2025-03-21T06:54:37: *** skipping scheduler with callIndex: 137 mismatch with 138
2025-03-21T06:56:50: Websocket: received message from server: ["snapshot"]
2025-03-21T06:56:51: server send: ["snapshot",{"playerInfo":{"version":"5.3.4","platform_version":"532_12_script_2024-12-07","cpuSerialNumber":"4000000067cf6998","legacyCpuSerialNumber":"","myIpAddress":"10.4.10.219 ","ethMac":"2c:cf:67:cf:69:98","wifiMac":"2c:cf:67:cf:69:99","name":"CDSTV2"},"data":"iVBORw0KGgoAAAANSUhEUgAAB4AAAAQ4CAIAAABnsVYUAAAgAElEQVR4nOzdd3xkdb3/8e+ZXjLpPbvZZHtn2cIuZYGlShEEFCx4RcSLgkq7gAUsKEVFmlJERX+IghSRjrRlG7vL9t6zu+m9TabPOef3x0xCykzqnJlJ8no+Ik5mzpzzPWdOZpP3+cznK6mqKgAAAAAAAAAAiDVdogcAAAAAAAAAABibCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAA
2025-03-21T06:57:22: max temperature:  50.15
2025-03-21T06:57:22: Player uptime :  86224.95
2025-03-21T06:57:22: server send: ["status",{"version":"5.3.4","platform_version":"532_12_script_2024-12-07","cpuSerialNumber":"4000000067cf6998","legacyCpuSerialNumber":"","myIpAddress":"10.4.10.219 ","ethMac":"2c:cf:67:cf:69:98","wifiMac":"2c:cf:67:cf:69:99","name":"CDSTV2"},{"diskSpaceUsed":"27%","diskSpaceAvailable":"20G","totalDiskSpace":"29G","wgetSpeed":0,"wgetBytes":"0K","downloadInProgress":false,"lastUpload":1742554306555,"syncInProgress":false,"tvStatus":true,"cecTvStatus":true,"isCecNotSupported":false,"licensed":true,"uptime":"86224.95","piTemperature":50.15,"currentPlaylist":"TESTING","playlistOn":true,"duration":null,"request":true},false]
2025-03-21T06:57:22: Websocket: received message from server: ["config",{"secret":"default","playlists":[{"name":"TESTING","settings":{"ads":{"adPlaylist":false,"adCount":1,"adInterval":60},"audio":{"enable":false,"random":false,"volume":50}},"skipForSchedule":false,"plType":"regular"}],"assets":["Bumper 1.local","Where Am I Owen.tv","dgst302.pdf","__TESTING.json"],"assetsValidity":[],"lastDeployed":"1742554306163","installation":"umwcds","TZ":"America/New_York","location":"Fredericksburg, VA","baseUrl":"/sync_folders/umwcds/","name":"CDSTV2","resolution":"1080p","orientation":"landscape","animationType":"right","animationEnable":false,"resizeAssets":true,"videoKeepAspect":false,"videoShowSubtitles":false,"imageLetterboxed":false,"brightness":{"defaults":{"control":"None","level":"Bright"},"schedule":[]},"sleep":{"enable":false},"reboot":{"enable":true,"time":"1970-01-01T12:00:00.000Z","absoluteTime":"07:00"},"signageBackgroundColor":"#000","omxVolume":100,"timeToStopVideo":120,"qrObj":{"show":false,"link":"https://pisignage.com","posX":"l","posY
2025-03-21T06:57:22: Getting screens for config,all as 0
2025-03-21T06:57:22: ****** send message for token: 798
2025-03-21T06:57:22: ****** resolve send message for token for screen: 0: 798
2025-03-21T06:57:22: Chrome executed script {"event":"COMMAND_EXECUTED","params":{"cmd":"config","params":{"animationType":"none"},"token":798},"token":798}
2025-03-21T06:57:37: Websocket: received message from server: ["snapshot"]
2025-03-21T06:57:37: server send: ["snapshot",{"playerInfo":{"version":"5.3.4","platform_version":"532_12_script_2024-12-07","cpuSerialNumber":"4000000067cf6998","legacyCpuSerialNumber":"","myIpAddress":"10.4.10.219 ","ethMac":"2c:cf:67:cf:69:98","wifiMac":"2c:cf:67:cf:69:99","name":"CDSTV2"},"data":"iVBORw0KGgoAAAANSUhEUgAAB4AAAAQ4CAIAAABnsVYUAAAgAElEQVR4nOzdd3xkdb3/8e+ZXjLpPbvZZHtn2cIuZYGlShEEFCx4RcSLgkq7gAUsKEVFmlJERX+IghSRjrRlG7vL9t6zu+m9TabPOef3x0xCykzqnJlJ8no+Ik5mzpzzPWdOZpP3+cznK6mqKgAAAAAAAAAAiDVdogcAAAAAAAAAABibCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAAaIIAGgAAAAAAAACgCQJoAAAAAAAAAIAmCKABAAAAAAAAAJoggAYAAAAAAAAA
2025-03-21T06:57:44: Websocket: received message from server: ["shell","tail -200 /home/pi/forever_out.log"]
2025-03-21T06:57:44: Executing shell command: tail -200 /home/pi/forever_out.log```

**Comment by zachwhalen** [comment]
I MAY be onto something... After trying several different arrangements and reading back through the logs, it seems that the problems arise when switching from a YouTube video to something else (like a PDF or PNG). In the logs, I am seeing something like 
```
2025-03-21T06:54:37: MEDIA_ENDED message from browser: https://youtu.be/RMipfgqQD2Y, zone: main and screen: 0
```
And I interpret that as a message from Youtube that the video has ended, and that message is disrupting the playlist's timer. 

I noticed that one of the YT videos I was testing with was listed at 64 seconds when I added it to PiSignage, but YouTube displays 63 seconds on the player controls. And then ffmpeg pegs it at 1:03.83.

Therefore, I think that YouTube is sending the MEDIA_ENDED message before pisignage expects it, which cancels the pisignage timer. 

To experiment, I rebuilt my playlist but set each YouTube asset's duration 2 seconds shorter than its actual duration. This worked great for a while, but it eventually got stuck again. It could be that -- for whatever reason -- pisignage took longer than 2 seconds to get the next asset started. Maybe a memory issue. I have this playlist on two Pis and they got stuck at different places.

So that may be something, but it isn't ideal if I have to arbitrarily truncate videos.

**Comment by zachwhalen** [comment]
I don't know if this needs to be a new issue, but basically: I continue to have a lot of trouble with YouTube content. The problems described in previous posts all occurred with Chromium as the group's media player. 

I tried VLC, which worked for a while, but with the following problems: 

1- video playback was at a significantly reduced resolution. This could be because youtube-dl is not caching the best quality version. 
2 - eventually, all playback of YouTube links failed. The logs show errors from `yt-dlp`. 

I'm not sure what the correct yt-dlp parameters should be, but I tried that in my terminal and got the same error result. (Version `2025.02.19`.)

Any ideas?

Log follows

```
2025-03-24T13:00:15: Getting video URL for https://youtu.be/oo46CLq0uU4 with yt-dlp
2025-03-24T13:00:15: Youtube video url not available, reason: exec error: Error: Command failed: yt-dlp -ciw -g -f b https://youtu.be/oo46CLq0uU4
2025-03-24T13:00:15: WARNING: [youtube] oo46CLq0uU4: nsig extraction failed: Some formats may be missing
2025-03-24T13:00:15:          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
2025-03-24T13:00:15:          n = j6u0r_8FfFAh9bPI ; player = https://www.youtube.com/s/player/643afba4/player_ias.vflset/en_US/base.js
2025-03-24T13:00:15: WARNING: [youtube] oo46CLq0uU4: nsig extraction failed: Some formats may be missing
2025-03-24T13:00:15:          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
2025-03-24T13:00:15:          n = -R6POweIWFaeGOeI ; player = https://www.youtube.com/s/player/643afba4/player_ias.vflset/en_US/base.js
2025-03-24T13:00:15: ERROR: [youtube] oo46CLq0uU4: Requested format is not available. Use --list-formats for a list of available formats
2025-03-24T13:00:15: 
2025-03-24T13:00:15: display next timer cancelled: main
2025-03-24T13:00:15: Zone: main, Playing next file: /media/_local_bumper_computer_8s.mkv of type video for duration 8 seconds;36;0
```

**Comment by colloqi** [comment]
We did a 5.3.5 release which should fix this error, can you try?

**Comment by zachwhalen** [comment]
I have upgraded both of my players to version 5.3.5/532_12_script_2024-12-07, but I am still getting errors with YouTube playback. In my test playlist, I have a single YouTube video asset ("Livestreaming or Youtube"), and it is not playing at all. I will share a relevant log excerpt below. 

In case it helps, I checked and the yt-dlp version is 2024.12.06.

For my application I've just been transferring video media to the local storage on the players, and that's working well. But I would still like to get the YouTube option working, if possible.

```
2025-04-04T12:56:01: [38280:38280:0404/125601.721113:ERROR:wayland_event_watcher.cc(47)] libwayland: warning: queue 0x4400110d80 destroyed while proxies still attached:
2025-04-04T12:56:01: 
2025-04-04T12:56:01: [38280:38280:0404/125601.721248:ERROR:wayland_event_watcher.cc(47)] libwayland:   wl_shm_pool#36 still attached
2025-04-04T12:56:01: 
2025-04-04T12:56:01: Youtube video url not available, reason: exec error: Error: Command failed: yt-dlp -ciw -g -f b https://www.youtube.com/watch?v=RMipfgqQD2Y
2025-04-04T12:56:01: WARNING: [youtube] RMipfgqQD2Y: nsig extraction failed: Some formats may be missing
2025-04-04T12:56:01:          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
2025-04-04T12:56:01:          n = tFPdJHCIdk0FgFj9g ; player = https://www.youtube.com/s/player/73381ccc/player_ias.vflset/en_US/base.js
2025-04-04T12:56:01: WARNING: [youtube] RMipfgqQD2Y: nsig extraction failed: Some formats may be missing
2025-04-04T12:56:01:          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
2025-04-04T12:56:01:          n = RDr3yB9RYFCwAK18q ; player = https://www.youtube.com/s/player/73381ccc/player_ias.vflset/en_US/base.js
2025-04-04T12:56:01: ERROR: [youtube] RMipfgqQD2Y: Requested format is not available. Use --list-formats for a list of available formats
2025-04-04T12:56:01: 
2025-04-04T12:56:06: Executing shell command: tail -200 ../forever_out.log```

**Comment by AbhijithBn** [comment]
Hi @zachwhalen 

We fixed a few issues in the default player. Can you change the Video player to "default" from Group Settings and check?
